version: '3.6'

services:
  nginx:
    image: ossobv/nginx
    ports:
    - "9092:9092"
    - "443:443"
    volumes:
    - ./default.conf:/etc/nginx/nginx.conf
    - ./stream_9092.log:/var/log/nginx/stream_9092.log
    - ./stream_443.log:/var/log/nginx/stream_443.log

  kafkacat:
    image: confluentinc/cp-kafkacat
    depends_on:
      - nginx
    links:
     - "nginx:${CCLOUD_BOOTSTRAP_SERVER_NO_PORT}"
    command:
      - bash
      - -c
      - |
        kafkacat -b ${CCLOUD_BOOTSTRAP_SERVER} -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN -X sasl.username=${CCLOUD_API_KEY} -X sasl.password=${CCLOUD_API_SECRET} -X api.version.request=true -t ${CCLOUD_TOPIC} -C -f '\nKey (%K bytes): %k\t\nValue (%S bytes): %s\n\Partition: %p\tOffset: %o\n--\n'
        sleep infinity